apiVersion: apps/v1
kind: Deployment
metadata:
  name: CICD
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  selector:
    matchLabels:
      app: cicd
  template:
    metadata:
      labels:
        app: cicd
    spec:
      containers:
       - name: app
         image: "{{ .Values.image.repository }}":"{{ .Values.image.tag }}"
