name: CICD with ArgoCD
on: push
jobs:
  CICDJob:
    env:
      imagename: "argocdimage"
    runs-on: ubuntu-latest
    steps:
     - name: checkout the repo
       uses: actions/checkout@v4
     - name: Setup Java 17
       uses: actions/setup-java@v4
       with:
         distribution: 'temurin'
         java-version: '17'
     - name: Build the code
       run: mvn package
     - name: Install docker
       uses: docker/setup-docker-action@v4
     - name: Login to Dockerhub
       uses: docker/login-action@v3
       with:
         username: ${{ secrets.DOCKERHUB_USERNAME }}
         password: ${{ secrets.DOCKERHUB_TOKEN }}
     - name: Build and Push
       uses: docker/build-push-action@v6
       with:
         context: .
         push: true
         tags: ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.imagename }}:${{ github.run.number }}
